# Static, hand-curated glossary of programming terms — the single source of
# truth for GlossaryHelper's auto-hover term wrapping across every section's
# rendered text. Drafted once with AI assistance, then hand-reviewed; nothing
# touches this file automatically again. Extend it by adding one line — keys
# must already be lowercase, since .lookup only downcases and strips its
# INPUT, never the stored keys.
module Glossary
  TERMS = {
    "abstraction" => "Hiding the messy details behind a simpler interface so callers only need to know what something does, not how.",
    "acid" => "Atomicity, Consistency, Isolation, Durability — the four guarantees a database transaction makes about behaving as a single, safe unit.",
    "adapter pattern" => "A wrapper that translates one interface into another so two incompatible pieces of code can work together.",
    "api versioning" => "Marking breaking changes to an API (e.g. /v1, /v2) so existing clients keep working while new ones adopt the new shape.",
    "arrow function" => "A shorthand JS function syntax that doesn't rebind `this`, inheriting it from the surrounding scope instead.",
    "array mutation" => "Changing an array in place (push, splice, sort) rather than creating a new one — can surprise code that expected the original to stay untouched.",
    "array mutation pitfalls" => "Changing an array in place (push, splice, sort) rather than creating a new one — can surprise code that expected the original to stay untouched.",
    "async/await" => "Syntax for writing asynchronous, promise-based code that reads top-to-bottom like synchronous code.",
    "authorization" => "Checking whether an already-identified user is allowed to perform a specific action, distinct from authentication (who they are).",
    "background job" => "Work queued to run outside the request/response cycle, so a slow task doesn't make the user wait for it.",
    "background jobs" => "Work queued to run outside the request/response cycle, so a slow task doesn't make the user wait for it.",
    "big o notation" => "A way to describe how an algorithm's time or memory use grows as its input grows, ignoring constant factors.",
    "blue-green deployment" => "Running two identical production environments and switching traffic from one to the other, so a release has an instant rollback path.",
    "build vs buy" => "The decision between building a capability in-house versus adopting an existing tool or vendor for it.",
    "bundler" => "A tool (e.g. esbuild, webpack) that combines many JavaScript modules into the smaller set of files a browser actually loads.",
    "cache invalidation" => "Deciding when cached data is stale and must be refreshed or removed — notoriously one of the two hard problems in computer science.",
    "caching" => "Storing the result of expensive work so a later request can reuse it instead of redoing the work.",
    "caching strategy" => "The set of decisions about what to cache, for how long, and how it gets invalidated, matched to how fresh the data needs to be.",
    "callback" => "A function passed into another function to be run later, often once some asynchronous work finishes.",
    "callback hell" => "Deeply nested callbacks that make asynchronous code hard to read and reason about, usually solved with promises or async/await.",
    "callbacks vs service objects" => "Choosing between a model lifecycle hook (before_save, after_create) and a standalone class to hold business logic that reaches beyond one model.",
    "callbacks vs service" => "Choosing between a model lifecycle hook (before_save, after_create) and a standalone class to hold business logic that reaches beyond one model.",
    "canary release" => "Rolling a change out to a small slice of traffic first, so a bad deploy affects a few users instead of everyone.",
    "circuit breaker" => "A safeguard that stops calling a failing dependency for a while after repeated failures, instead of retrying into a wall.",
    "closure" => "A function that remembers the variables from where it was defined, even after that outer scope has finished running.",
    "closures" => "A function that remembers the variables from where it was defined, even after that outer scope has finished running.",
    "closures in loops" => "A classic bug where every closure created inside a loop captures the same variable binding, not a snapshot of its value at that iteration.",
    "code splitting" => "Breaking a JS bundle into smaller chunks that load only when needed, instead of one large file up front.",
    "component re-renders" => "A UI framework re-running a component's render function in response to a state or prop change — worth watching for when it happens more often than the actual output changed.",
    "component re renders" => "A UI framework re-running a component's render function in response to a state or prop change — worth watching for when it happens more often than the actual output changed.",
    "composite index" => "A database index built across multiple columns together, useful when queries filter or sort by that same combination.",
    "composition over inheritance" => "Preferring to build behavior by combining small, focused objects rather than by extending a class hierarchy.",
    "concern" => "A module mixed into a Rails model or controller to share behavior across classes without deep inheritance.",
    "concurrency" => "Multiple pieces of work making progress during overlapping time periods, which introduces the possibility of race conditions.",
    "context api" => "React's built-in way to pass data down a component tree without threading props through every intermediate level.",
    "controlled component" => "A form input whose value is driven entirely by React state, with every change going through a handler.",
    "controlled vs uncontrolled" => "The choice between a form input whose value lives in framework state (controlled) and one that manages its own value internally, read only when needed via a ref (uncontrolled).",
    "coupling and cohesion" => "How entangled separate parts of a system are with each other (coupling) versus how focused a single part is on one responsibility (cohesion).",
    "coupling cohesion" => "How entangled separate parts of a system are with each other (coupling) versus how focused a single part is on one responsibility (cohesion).",
    "cron" => "A schedule for running a job automatically at fixed times or intervals, without a person triggering it.",
    "csrf" => "Cross-Site Request Forgery — an attack that tricks a logged-in user's browser into submitting a request they didn't intend, defended against with per-session tokens.",
    "currying" => "Transforming a function that takes multiple arguments into a sequence of functions that each take one argument.",
    "data consistency tradeoffs" => "The tension between keeping data always correct everywhere (strong consistency) and accepting brief staleness for speed and availability (eventual consistency).",
    "data ownership" => "Which single service or team is the authoritative source of truth for a piece of data, so other consumers read a copy rather than mutate it directly.",
    "deadlock" => "Two or more processes each waiting on a resource the other holds, so neither can ever proceed.",
    "debouncing" => "Delaying a function's execution until a burst of calls has paused for a set time, so only the last one actually runs.",
    "debouncing throttling" => "Two related techniques for limiting how often a function runs in response to rapid events — debouncing waits for a pause before running, throttling caps the rate no matter how often it's triggered.",
    "decorator pattern" => "Wrapping an object to add behavior to it without changing its own class.",
    "denormalization" => "Duplicating data across tables to speed up reads, at the cost of having to keep the copies in sync on writes.",
    "denormalization tradeoffs" => "Deliberately duplicating data to make reads cheaper, accepting that every copy is now something you have to keep in sync.",
    "dependency injection" => "Supplying an object's dependencies from outside rather than having it construct them itself, making the object easier to test and swap.",
    "destructuring" => "JS/TS syntax for unpacking values from an array or object into individual variables in one statement.",
    "discriminated union" => "A TypeScript union type where each variant carries a common tag field, letting the compiler narrow which shape you're dealing with.",
    "dry" => "Don't Repeat Yourself — every piece of knowledge should have a single, unambiguous representation in a system.",
    "duck typing" => "Treating an object as usable based on what methods it responds to, not on its declared class or type.",
    "eager loading" => "Fetching associated records up front in one query, avoiding the N+1 problem of fetching them one at a time later.",
    "enum" => "A type restricted to a fixed set of named values, used to make an otherwise-stringly-typed field self-documenting and exhaustive.",
    "error handling" => "Deciding what a program does when something goes wrong — rescue, retry, log, or surface — rather than letting a failure propagate unchecked.",
    "event-driven vs request-response" => "Choosing between systems that react to published events asynchronously versus ones where a caller waits synchronously for a direct reply.",
    "event driven vs request response" => "Choosing between systems that react to published events asynchronously versus ones where a caller waits synchronously for a direct reply.",
    "event emitter" => "An object other code can subscribe to, which then broadcasts events to every listener when something happens.",
    "event loop" => "The mechanism that lets a single-threaded language like JS handle asynchronous work by processing tasks and callbacks from a queue.",
    "event loop blocking" => "Long-running synchronous code that hogs the event loop, freezing everything else — timers, I/O, rendering — until it finishes.",
    "exponential backoff" => "Waiting progressively longer between retries after a failure, so a struggling dependency isn't hammered with immediate retries.",
    "failure mode design" => "Deliberately planning how a system behaves when a dependency fails, instead of only designing for the happy path.",
    "feature envy" => "A method that reaches into another object's data more than its own, a sign the logic it performs belongs on that other object instead.",
    "feature flag" => "A toggle that turns a piece of functionality on or off without a deploy, often used to roll changes out gradually.",
    "first-class function" => "A function that can be assigned to a variable, passed as an argument, and returned from another function, like any other value.",
    "foreign key" => "A column that references another table's primary key, used by the database to enforce that the referenced row actually exists.",
    "garbage collection" => "Automatic reclamation of memory no longer reachable by the running program, so the developer doesn't manually free it.",
    "generics" => "Writing a function or type that works over a range of types while still preserving type information, instead of using `any`.",
    "god object" => "A single class or module that has grown to know or do far more than its name suggests, coupling unrelated responsibilities together.",
    "hoisting" => "JS's behavior of moving variable and function declarations to the top of their scope before code runs — though only the declaration, not the assignment.",
    "hooks dependencies" => "The array passed to a React hook (useEffect, useMemo) that tells it which values to watch, re-running the hook when any of them change.",
    "horizontal scaling" => "Handling more load by adding more machines running the same code, as opposed to making one machine more powerful.",
    "idempotency" => "A property where performing the same operation multiple times has the same effect as performing it once.",
    "idempotency at scale" => "Designing a distributed operation so a retry after a network failure never double-applies its effect, even without knowing whether the first attempt actually landed.",
    "idempotent" => "A property where performing the same operation multiple times has the same effect as performing it once.",
    "immutability" => "Data that can't be changed after it's created — any 'change' produces a new value instead of mutating the original.",
    "indexing" => "A database structure that speeds up lookups on a column at the cost of extra storage and slower writes.",
    "inheritance" => "One class acquiring the behavior and structure of another (its parent), typically extending or overriding it.",
    "insecure client storage" => "Keeping sensitive data (tokens, secrets) in localStorage or a cookie without the protections that make it safe from theft, e.g. via XSS.",
    "inversion of control" => "Framework or container code calling into your code, rather than your code driving the call — the framework decides when your code runs.",
    "jwt" => "JSON Web Token — a signed, self-contained token that carries claims (like user identity) a server can verify without a database lookup.",
    "lazy loading" => "Deferring the loading of data or code until it's actually needed, rather than up front.",
    "load balancer" => "A layer that distributes incoming requests across multiple servers so no single one is overwhelmed.",
    "mapped conditional types" => "TypeScript features for deriving a new type from an existing one — a mapped type transforms each property, a conditional type branches on a type-level condition.",
    "mass assignment" => "Setting many model attributes at once from a hash of params — dangerous unless the allowed attributes are explicitly restricted.",
    "mass assignment protection" => "Setting many model attributes at once from a hash of params — dangerous unless the allowed attributes are explicitly restricted.",
    "memoization" => "Caching a function's return value for a given input so a later call with the same input skips the work.",
    "memory leak" => "Memory that's no longer needed but never gets freed, because something still holds a reference to it — often an event listener that was never removed.",
    "memory leaks listeners" => "Memory that's no longer needed but never gets freed, because something still holds a reference to it — often an event listener that was never removed.",
    "metaprogramming" => "Code that writes or modifies code at runtime, e.g. dynamically defining methods rather than writing them out by hand.",
    "method_missing" => "A Ruby hook that intercepts calls to methods that don't exist, letting an object handle them dynamically instead of raising immediately.",
    "microtask queue" => "The higher-priority JS task queue (promise callbacks, queueMicrotask) that always drains fully before the next macrotask (setTimeout, I/O) runs.",
    "middleware" => "Code that sits in the request/response pipeline and can inspect, modify, or short-circuit a request before it reaches the app, or a response before it leaves.",
    "migration" => "A versioned, reversible script that changes a database schema, so schema changes are tracked and reproducible across environments.",
    "missing constraint" => "A rule the data must obey — not null, unique, a valid foreign key — that lives only in application code, so anything writing to the database directly can violate it.",
    "missing index" => "A column the database searches often but has no index for, so each lookup scans the whole table instead of jumping straight to the rows.",
    "mixin" => "A module of reusable methods 'mixed into' a class, giving it that behavior without inheriting from another class.",
    "mock" => "A test double that stands in for a real object and asserts it was called in the expected way.",
    "mutex" => "A lock that lets only one thread access a shared resource at a time, preventing concurrent modification.",
    "n+1" => "A performance bug where fetching a list triggers one query per item's association, instead of one query for the whole list up front.",
    "n_plus_one" => "A performance bug where fetching a list triggers one query per item's association, instead of one query for the whole list up front.",
    "normalization" => "Structuring database tables to minimize duplicated data, so each fact is stored in exactly one place.",
    "nullish coalescing" => "The `??` operator, which falls back to a default only when the left side is null or undefined — unlike `||`, it doesn't treat 0 or '' as missing.",
    "observability tradeoffs" => "The balance between how much logging/metrics/tracing a system emits and the cost, performance overhead, and noise that comes with it.",
    "observer pattern" => "Objects (observers) subscribing to notifications from another object (the subject) whenever its state changes.",
    "optimistic locking" => "Detecting a conflicting concurrent update by checking a version number at save time, rather than locking the row for the whole transaction.",
    "optional chaining" => "The `?.` operator, which short-circuits to undefined instead of throwing when accessing a property on something that might be null or undefined.",
    "orm" => "Object-Relational Mapping — a library that lets you work with database rows as objects instead of writing raw SQL.",
    "over-mocking" => "Stubbing out so much of the system under test that the test verifies the mocks were called correctly rather than that the real behavior works.",
    "over mocking" => "Stubbing out so much of the system under test that the test verifies the mocks were called correctly rather than that the real behavior works.",
    "pessimistic locking" => "Locking a row for the duration of a transaction so no other transaction can touch it, trading concurrency for certainty.",
    "policy object" => "A class that centralizes an authorization decision (can this user do this?) instead of scattering permission checks through controllers.",
    "policy objects" => "A class that centralizes an authorization decision (can this user do this?) instead of scattering permission checks through controllers.",
    "polymorphism" => "Different objects responding to the same method call in ways specific to their own type.",
    "primitive obsession" => "Representing a domain concept with a raw primitive (a string, a number) instead of a type of its own, losing the validation and meaning a dedicated object would carry.",
    "promise" => "An object representing the eventual result (or failure) of an asynchronous operation, which callbacks or await can attach to.",
    "promise chaining" => "Attaching a sequence of `.then()` calls to run asynchronous steps in order, each receiving the previous step's result.",
    "props drilling" => "Passing a prop down through several React components that don't use it themselves, just to reach a deeply nested child.",
    "prototype chain" => "The lookup path JS follows when a property isn't found directly on an object, walking up through the objects it inherits from.",
    "pub/sub" => "A messaging pattern where publishers emit events without knowing who's listening, and subscribers receive events without knowing who sent them.",
    "pure function" => "A function whose output depends only on its inputs and that causes no observable side effects, making it predictable and easy to test.",
    "query object" => "A class that encapsulates a specific, reusable database query, keeping complex query logic out of the model.",
    "query objects" => "A class that encapsulates a specific, reusable database query, keeping complex query logic out of the model.",
    "race condition" => "A bug where the outcome depends on the unpredictable timing of concurrent operations, e.g. two requests reading-then-writing the same value.",
    "rate limiting" => "Capping how many requests a client can make in a given time window, to protect a system from overload or abuse.",
    "reading for intent" => "Reading code or a request for what it's trying to accomplish, not just what it literally does — the difference between spotting a bug and spotting a mismatch between the code and its actual goal.",
    "recursion" => "A function that calls itself to solve a smaller version of the same problem, until it reaches a base case.",
    "reconciliation" => "React's algorithm for comparing a new virtual DOM tree to the previous one and updating only what actually changed in the real DOM.",
    "referential integrity" => "The database guarantee that a foreign key always points to a row that actually exists.",
    "replication" => "Keeping copies of a database on multiple servers, for redundancy and to spread out read load.",
    "retry logic" => "Automatically re-attempting a failed operation, usually with backoff, instead of surfacing the failure immediately.",
    "rollback" => "Reversing a database migration back to its previous schema state.",
    "scaling bottlenecks" => "The specific components (a database, a single-threaded service) that stop a system from handling more load, even after adding more of everything else.",
    "scope chaining" => "Combining multiple ActiveRecord scopes into one query by calling them in sequence.",
    "seed data" => "Pre-populated records loaded into a database, typically for local development or a fresh environment.",
    "separating symptom from cause" => "Distinguishing what a bug or complaint looks like on the surface from what's actually producing it, so a fix addresses the root cause rather than papering over its visible effect.",
    "service boundaries" => "The lines drawn between separate services in a system, defining what each one owns and how they're allowed to talk to each other.",
    "service object" => "A plain class that holds a single business operation, used when logic doesn't naturally belong on a model or in a controller.",
    "service objects" => "A plain class that holds a single business operation, used when logic doesn't naturally belong on a model or in a controller.",
    "sharding" => "Splitting a dataset across multiple databases, each holding a subset of the rows, to scale beyond what one database can hold.",
    "shotgun surgery" => "A single change that forces small edits across many unrelated classes or files, a sign the behavior it touches isn't consolidated anywhere.",
    "side effect" => "Any change a function makes beyond returning a value — writing to a variable outside itself, doing I/O, mutating an argument.",
    "single responsibility principle" => "The idea that a class or module should have exactly one reason to change.",
    "singleton pattern" => "Ensuring a class has exactly one instance, with a single global point of access to it.",
    "spotting unstated assumptions" => "Noticing where a plan, request, or piece of code silently assumes something it never says outright — an input's shape, an ordering, an edge case treated as fine — before that assumption causes trouble.",
    "spread operator" => "The `...` syntax for expanding an array or object's elements/properties into another array, object, or argument list.",
    "sql injection" => "An attack where untrusted input is concatenated directly into a SQL query, letting an attacker run arbitrary SQL — prevented by parameterized queries.",
    "sql injection prevention" => "An attack where untrusted input is concatenated directly into a SQL query, letting an attacker run arbitrary SQL — prevented by parameterized queries.",
    "stack vs heap" => "Two regions of memory: the stack holds fixed-size, short-lived data tied to function calls; the heap holds dynamically allocated data that outlives a single call.",
    "state lifting" => "Moving state up to the nearest common ancestor component so multiple children can share and stay in sync with it.",
    "state management" => "The approach an app uses to store and update shared data (local component state, context, or a dedicated store).",
    "static site generation" => "Rendering pages to static HTML at build time rather than on every request, trading flexibility for speed and simplicity.",
    "strategy pattern" => "Encapsulating interchangeable algorithms behind a common interface, so the caller can swap which one runs without changing its own code.",
    "strict mode" => "An opt-in JS mode that turns silent mistakes (like assigning to an undeclared variable) into thrown errors.",
    "stub" => "A test double that returns a canned response when called, without asserting how it was called.",
    "sync vs async" => "Choosing between code that waits for an operation to finish before continuing (sync) and code that keeps running while the operation completes in the background (async).",
    "temporal dead zone" => "The span between entering a scope and a `let`/`const` variable's declaration line, during which referencing it throws instead of returning undefined.",
    "testing implementation not behavior" => "Writing a test that breaks when internal code is refactored even though external behavior didn't change — a sign the test is coupled to how, not what.",
    "this binding" => "How JS determines what `this` refers to inside a function, which depends on how the function is called, not where it's defined (except for arrow functions).",
    "thread pool" => "A fixed set of reusable worker threads that pick up queued work, avoiding the cost of creating a new thread per task.",
    "thread safety" => "Code that behaves correctly when accessed by multiple threads at once, without needing external synchronization.",
    "throttling" => "Limiting a function to run at most once per fixed interval, no matter how often it's triggered.",
    "transaction" => "A group of database operations that all succeed together or all roll back together, so the database is never left half-updated.",
    "transaction isolation level" => "How much one in-progress transaction can see of another's uncommitted changes, trading consistency guarantees for concurrency.",
    "transaction safety" => "Making sure a multi-step database operation either fully applies or fully rolls back, so a failure partway through never leaves related records out of sync.",
    "tree shaking" => "A bundler optimization that removes exported code nobody actually imports, shrinking the final bundle.",
    "two-way binding" => "A form pattern where a UI input both displays and updates a piece of state automatically, without a separate change handler.",
    "type guard" => "A runtime check (like `typeof` or `instanceof`) that lets TypeScript narrow a variable to a more specific type within a block.",
    "type guards narrowing" => "A runtime check (like `typeof` or `instanceof`) that lets TypeScript narrow a variable to a more specific type within a block.",
    "type inference" => "A type system figuring out a value's type from context, without the developer writing an explicit annotation.",
    "union type" => "A TypeScript type that can be one of several specified types, e.g. `string | number`.",
    "union intersection types" => "A TypeScript type that can be one of several specified types, e.g. `string | number`.",
    "unidirectional data flow" => "Data moving in one direction through an app (e.g. parent to child, store to component), making state changes easier to trace.",
    "unsafe migration" => "A schema change that locks a table or rewrites it in place, blocking reads and writes for as long as it runs — usually avoidable by splitting it across deploys.",
    "validations" => "Rules on a model that reject invalid data before it's saved — the app-level counterpart to a database constraint.",
    "virtual dom" => "An in-memory representation of the UI that a library like React diffs against the previous version to compute the minimal real DOM update.",
    "webhook" => "An HTTP callback a service sends to a URL you provide when an event happens, instead of you polling for it.",
    "wrong cardinality" => "Modelling a relationship with the wrong shape — one-to-one where the real world has many, or a join table missing entirely — so the schema cannot represent cases the business actually has.",
    "xss" => "Cross-Site Scripting — an attack where untrusted input is rendered as executable script in another user's browser, prevented by escaping output.",
    "xss prevention" => "Cross-Site Scripting — an attack where untrusted input is rendered as executable script in another user's browser, prevented by escaping output.",
    "yagni" => "You Aren't Gonna Need It — a reminder not to build functionality speculatively, before there's an actual requirement for it."
  }.freeze

  def self.lookup(term)
    TERMS[term.to_s.strip.downcase]
  end

  # One compiled alternation over every curated term, built once at load time
  # rather than looping GlossaryHelper's word-boundary match per term per
  # render (~170 terms × every text field on every section, on every page
  # load — history alone renders up to 10 days' worth). Longest-key-first
  # ordering makes the alternation itself resolve overlapping terms (e.g.
  # "array mutation" vs. "array mutation pitfalls") in favor of the longer
  # match: at a given start position, regex alternation tries each branch in
  # the order listed and takes the first that matches, so a shorter term
  # listed first would win even where a longer one also fits. Each term
  # keeps its own \b...\b/i sub-pattern (matching GlossaryHelper's prior
  # per-term behavior) rather than one shared /i flag, since Regexp.union
  # preserves each argument's own compiled options.
  TERM_PATTERN = Regexp.union(
    TERMS.keys.sort_by { |term| -term.length }.map { |term| /\b#{Regexp.escape(term)}\b/i }
  )
end
